project:
  type: website
  output-dir: docs

website:
  title: ""
  search: false
  navbar:
    logo: "images/title.png"
    left:
      - href: index.qmd
        text: Inici
      - href: about.qmd
        text: Sobre
      - href: team.qmd
        text: Equip
      - href: submission.qmd
        text: Presentaci√≥
      - href: contact.qmd
        text: Contacte
  page-footer: 
    center: FLOh!RA Copyright 2026
    border: true
    background: dark

format:
  html:
    theme: pulse
    backgroundcolor: "#F6EDDE"
    fonts:
        heading: "Montserrat"
        body: "Inter"



